DROP SEQUENCE IF EXISTS seq_country;
CREATE SEQUENCE seq_country
MINVALUE 1
MAXVALUE 99999999999999
START WITH 1
INCREMENT BY 1
NOCACHE
;

DROP TABLE IF EXISTS country;
CREATE TABLE country (
  id number(19) not null,
  short_name nvarchar2(255),
  name nvarchar2(255)
);

INSERT INTO country(id, short_name, name) VALUES
(seq_country.nextval, 'AF','Afghanistan'),
(seq_country.nextval, 'AL','Albania'),
(seq_country.nextval, 'DZ','Algeria'),
(seq_country.nextval, 'AS','American Samoa'),
(seq_country.nextval, 'AD','Andorra'),
(seq_country.nextval, 'AO','Angola'),
(seq_country.nextval, 'AI','Anguilla'),
(seq_country.nextval, 'AQ','Antarctica'),
(seq_country.nextval, 'AG','Antigua And Barbuda'),
(seq_country.nextval, 'AR','Argentina'),
(seq_country.nextval, 'AM','Armenia'),
(seq_country.nextval, 'AW','Aruba'),
(seq_country.nextval, 'AU','Australia'),
(seq_country.nextval, 'AT','Austria'),
(seq_country.nextval, 'AZ','Azerbaijan'),
(seq_country.nextval, 'BS','Bahamas'),
(seq_country.nextval, 'BH','Bahrain'),
(seq_country.nextval, 'BD','Bangladesh'),
(seq_country.nextval, 'BB','Barbados'),
(seq_country.nextval, 'BY','Belarus'),
(seq_country.nextval, 'BE','Belgium'),
(seq_country.nextval, 'BZ','Belize'),
(seq_country.nextval, 'BJ','Benin'),
(seq_country.nextval, 'BM','Bermuda'),
(seq_country.nextval, 'BT','Bhutan'),
(seq_country.nextval, 'BO','Bolivia'),
(seq_country.nextval, 'BA','Bosnia And Herzegovina'),
(seq_country.nextval, 'BW','Botswana'),
(seq_country.nextval, 'BV','Bouvet Island'),
(seq_country.nextval, 'BR','Brazil'),
(seq_country.nextval, 'IO','British Indian Ocean Territory'),
(seq_country.nextval, 'BN','Brunei Darussalam'),
(seq_country.nextval, 'BG','Bulgaria'),
(seq_country.nextval, 'BF','Burkina Faso'),
(seq_country.nextval, 'BI','Burundi'),
(seq_country.nextval, 'KH','Cambodia'),
(seq_country.nextval, 'CM','Cameroon'),
(seq_country.nextval, 'CA','Canada'),
(seq_country.nextval, 'CV','Cape Verde'),
(seq_country.nextval, 'KY','Cayman Islands'),
(seq_country.nextval, 'CF','Central African Republic'),
(seq_country.nextval, 'TD','Chad'),
(seq_country.nextval, 'CL','Chile'),
(seq_country.nextval, 'CN','China'),
(seq_country.nextval, 'CX','Christmas Island'),
(seq_country.nextval, 'CC','Cocos (keeling) Islands'),
(seq_country.nextval, 'CO','Colombia'),
(seq_country.nextval, 'KM','Comoros'),
(seq_country.nextval, 'CG','Congo'),
(seq_country.nextval, 'CD','Congo, The Democratic Republic Of The'),
(seq_country.nextval, 'CK','Cook Islands'),
(seq_country.nextval, 'CR','Costa Rica'),
(seq_country.nextval, 'CI','Cote Divoire'),
(seq_country.nextval, 'HR','Croatia'),
(seq_country.nextval, 'CU','Cuba'),
(seq_country.nextval, 'CY','Cyprus'),
(seq_country.nextval, 'CZ','Czech Republic'),
(seq_country.nextval, 'DK','Denmark'),
(seq_country.nextval, 'DJ','Djibouti'),
(seq_country.nextval, 'DM','Dominica'),
(seq_country.nextval, 'DO','Dominican Republic'),
(seq_country.nextval, 'TP','East Timor'),
(seq_country.nextval, 'EC','Ecuador'),
(seq_country.nextval, 'EG','Egypt'),
(seq_country.nextval, 'SV','El Salvador'),
(seq_country.nextval, 'GQ','Equatorial Guinea'),
(seq_country.nextval, 'ER','Eritrea'),
(seq_country.nextval, 'EE','Estonia'),
(seq_country.nextval, 'ET','Ethiopia'),
(seq_country.nextval, 'FK','Falkland Islands (malvinas)'),
(seq_country.nextval, 'FO','Faroe Islands'),
(seq_country.nextval, 'FJ','Fiji'),
(seq_country.nextval, 'FI','Finland'),
(seq_country.nextval, 'FR','France'),
(seq_country.nextval, 'GF','French Guiana'),
(seq_country.nextval, 'PF','French Polynesia'),
(seq_country.nextval, 'TF','French Southern Territories'),
(seq_country.nextval, 'GA','Gabon'),
(seq_country.nextval, 'GM','Gambia'),
(seq_country.nextval, 'GE','Georgia'),
(seq_country.nextval, 'DE','Germany'),
(seq_country.nextval, 'GH','Ghana'),
(seq_country.nextval, 'GI','Gibraltar'),
(seq_country.nextval, 'GR','Greece'),
(seq_country.nextval, 'GL','Greenland'),
(seq_country.nextval, 'GD','Grenada'),
(seq_country.nextval, 'GP','Guadeloupe'),
(seq_country.nextval, 'GU','Guam'),
(seq_country.nextval, 'GT','Guatemala'),
(seq_country.nextval, 'GN','Guinea'),
(seq_country.nextval, 'GW','Guinea-bissau'),
(seq_country.nextval, 'GY','Guyana'),
(seq_country.nextval, 'HT','Haiti'),
(seq_country.nextval, 'HM','Heard Island And Mcdonald Islands'),
(seq_country.nextval, 'VA','Holy See (vatican City State)'),
(seq_country.nextval, 'HN','Honduras'),
(seq_country.nextval, 'HK','Hong Kong'),
(seq_country.nextval, 'HU','Hungary'),
(seq_country.nextval, 'IS','Iceland'),
(seq_country.nextval, 'IN','India'),
(seq_country.nextval, 'ID','Indonesia'),
(seq_country.nextval, 'IR','Iran, Islamic Republic Of'),
(seq_country.nextval, 'IQ','Iraq'),
(seq_country.nextval, 'IE','Ireland'),
(seq_country.nextval, 'IL','Israel'),
(seq_country.nextval, 'IT','Italy'),
(seq_country.nextval, 'JM','Jamaica'),
(seq_country.nextval, 'JP','Japan'),
(seq_country.nextval, 'JO','Jordan'),
(seq_country.nextval, 'KZ','Kazakstan'),
(seq_country.nextval, 'KE','Kenya'),
(seq_country.nextval, 'KI','Kiribati'),
(seq_country.nextval, 'KP','Korea, Democratic Peoples Republic Of'),
(seq_country.nextval, 'KR','Korea, Republic Of'),
(seq_country.nextval, 'KV','Kosovo'),
(seq_country.nextval, 'KW','Kuwait'),
(seq_country.nextval, 'KG','Kyrgyzstan'),
(seq_country.nextval, 'LA','Lao Peoples Democratic Republic'),
(seq_country.nextval, 'LV','Latvia'),
(seq_country.nextval, 'LB','Lebanon'),
(seq_country.nextval, 'LS','Lesotho'),
(seq_country.nextval, 'LR','Liberia'),
(seq_country.nextval, 'LY','Libyan Arab Jamahiriya'),
(seq_country.nextval, 'LI','Liechtenstein'),
(seq_country.nextval, 'LT','Lithuania'),
(seq_country.nextval, 'LU','Luxembourg'),
(seq_country.nextval, 'MO','Macau'),
(seq_country.nextval, 'MK','Macedonia, The Former Yugoslav Republic Of'),
(seq_country.nextval, 'MG','Madagascar'),
(seq_country.nextval, 'MW','Malawi'),
(seq_country.nextval, 'MY','Malaysia'),
(seq_country.nextval, 'MV','Maldives'),
(seq_country.nextval, 'ML','Mali'),
(seq_country.nextval, 'MT','Malta'),
(seq_country.nextval, 'MH','Marshall Islands'),
(seq_country.nextval, 'MQ','Martinique'),
(seq_country.nextval, 'MR','Mauritania'),
(seq_country.nextval, 'MU','Mauritius'),
(seq_country.nextval, 'YT','Mayotte'),
(seq_country.nextval, 'MX','Mexico'),
(seq_country.nextval, 'FM','Micronesia, Federated States Of'),
(seq_country.nextval, 'MD','Moldova, Republic Of'),
(seq_country.nextval, 'MC','Monaco'),
(seq_country.nextval, 'MN','Mongolia'),
(seq_country.nextval, 'MS','Montserrat'),
(seq_country.nextval, 'ME','Montenegro'),
(seq_country.nextval, 'MA','Morocco'),
(seq_country.nextval, 'MZ','Mozambique'),
(seq_country.nextval, 'MM','Myanmar'),
(seq_country.nextval, 'NA','Namibia'),
(seq_country.nextval, 'NR','Nauru'),
(seq_country.nextval, 'NP','Nepal'),
(seq_country.nextval, 'NL','Netherlands'),
(seq_country.nextval, 'AN','Netherlands Antilles'),
(seq_country.nextval, 'NC','New Caledonia'),
(seq_country.nextval, 'NZ','New Zealand'),
(seq_country.nextval, 'NI','Nicaragua'),
(seq_country.nextval, 'NE','Niger'),
(seq_country.nextval, 'NG','Nigeria'),
(seq_country.nextval, 'NU','Niue'),
(seq_country.nextval, 'NF','Norfolk Island'),
(seq_country.nextval, 'MP','Northern Mariana Islands'),
(seq_country.nextval, 'NO','Norway'),
(seq_country.nextval, 'OM','Oman'),
(seq_country.nextval, 'PK','Pakistan'),
(seq_country.nextval, 'PW','Palau'),
(seq_country.nextval, 'PS','Palestinian Territory, Occupied'),
(seq_country.nextval, 'PA','Panama'),
(seq_country.nextval, 'PG','Papua New Guinea'),
(seq_country.nextval, 'PY','Paraguay'),
(seq_country.nextval, 'PE','Peru'),
(seq_country.nextval, 'PH','Philippines'),
(seq_country.nextval, 'PN','Pitcairn'),
(seq_country.nextval, 'PL','Poland'),
(seq_country.nextval, 'PT','Portugal'),
(seq_country.nextval, 'PR','Puerto Rico'),
(seq_country.nextval, 'QA','Qatar'),
(seq_country.nextval, 'RE','Reunion'),
(seq_country.nextval, 'RO','Romania'),
(seq_country.nextval, 'RU','Russian Federation'),
(seq_country.nextval, 'RW','Rwanda'),
(seq_country.nextval, 'SH','Saint Helena'),
(seq_country.nextval, 'KN','Saint Kitts And Nevis'),
(seq_country.nextval, 'LC','Saint Lucia'),
(seq_country.nextval, 'PM','Saint Pierre And Miquelon'),
(seq_country.nextval, 'VC','Saint Vincent And The Grenadines'),
(seq_country.nextval, 'WS','Samoa'),
(seq_country.nextval, 'SM','San Marino'),
(seq_country.nextval, 'ST','Sao Tome And Principe'),
(seq_country.nextval, 'SA','Saudi Arabia'),
(seq_country.nextval, 'SN','Senegal'),
(seq_country.nextval, 'RS','Serbia'),
(seq_country.nextval, 'SC','Seychelles'),
(seq_country.nextval, 'SL','Sierra Leone'),
(seq_country.nextval, 'SG','Singapore'),
(seq_country.nextval, 'SK','Slovakia'),
(seq_country.nextval, 'SI','Slovenia'),
(seq_country.nextval, 'SB','Solomon Islands'),
(seq_country.nextval, 'SO','Somalia'),
(seq_country.nextval, 'ZA','South Africa'),
(seq_country.nextval, 'GS','South Georgia And The South Sandwich Islands'),
(seq_country.nextval, 'ES','Spain'),
(seq_country.nextval, 'LK','Sri Lanka'),
(seq_country.nextval, 'SD','Sudan'),
(seq_country.nextval, 'SR','Suriname'),
(seq_country.nextval, 'SJ','Svalbard And Jan Mayen'),
(seq_country.nextval, 'SZ','Swaziland'),
(seq_country.nextval, 'SE','Sweden'),
(seq_country.nextval, 'CH','Switzerland'),
(seq_country.nextval, 'SY','Syrian Arab Republic'),
(seq_country.nextval, 'TW','Taiwan, Province Of China'),
(seq_country.nextval, 'TJ','Tajikistan'),
(seq_country.nextval, 'TZ','Tanzania, United Republic Of'),
(seq_country.nextval, 'TH','Thailand'),
(seq_country.nextval, 'TG','Togo'),
(seq_country.nextval, 'TK','Tokelau'),
(seq_country.nextval, 'TO','Tonga'),
(seq_country.nextval, 'TT','Trinidad And Tobago'),
(seq_country.nextval, 'TN','Tunisia'),
(seq_country.nextval, 'TR','Turkey'),
(seq_country.nextval, 'TM','Turkmenistan'),
(seq_country.nextval, 'TC','Turks And Caicos Islands'),
(seq_country.nextval, 'TV','Tuvalu'),
(seq_country.nextval, 'UG','Uganda'),
(seq_country.nextval, 'UA','Ukraine'),
(seq_country.nextval, 'AE','United Arab Emirates'),
(seq_country.nextval, 'GB','United Kingdom'),
(seq_country.nextval, 'US','United States'),
(seq_country.nextval, 'UM','United States Minor Outlying Islands'),
(seq_country.nextval, 'UY','Uruguay'),
(seq_country.nextval, 'UZ','Uzbekistan'),
(seq_country.nextval, 'VU','Vanuatu'),
(seq_country.nextval, 'VE','Venezuela'),
(seq_country.nextval, 'VN','Viet Nam'),
(seq_country.nextval, 'VG','Virgin Islands, British'),
(seq_country.nextval, 'VI','Virgin Islands, U.s.'),
(seq_country.nextval, 'WF','Wallis And Futuna'),
(seq_country.nextval, 'EH','Western Sahara'),
(seq_country.nextval, 'YE','Yemen'),
(seq_country.nextval, 'ZM','Zambia'),
(seq_country.nextval, 'ZW','Zimbabwe');
